#!/bin/sh
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle start script
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions "$var", "${var}", "${var:-default}", "${#var}", "${var%suffix}", "${var##prefix}";
#         * compound commands having a status, especially case;
#         * various built-in commands including command, set, and local.
#
#   Important for patching:
#
#   (2) When you fix the bug, make sure you add a test case which fails on the old code and passes on the new code.
#   (3) Go to the directory $(cd "$(dirname "$0")"; pwd -P) and run `gradlew --version`.
#   (4) The test will pass on all platforms.
#
#   Important for migrating existing Enterprise builds:
#
#   (5) Review our migration guide at https://guides.gradle.org/migrating-build-logic-for-production-use/
#
#   (6) Run using this wrapper by typing `./gradlew` (on Unix) or `gradlew.bat` (on Windows).
#
#   (7) Inspect the generated wrapper Java classes under version control.
#
##############################################################################

GRADLE_APP_NAME="Gradle"
APP_ABS_PATH=`pwd`

# Need this for daisy-chained symlinks.
while
    APP_HOME=`dirname "$PRG"`/..
    [ -d "$APP_HOME" ]
do
    PRG=`ls -ld "$PRG"` ||
    break
done
APP_HOME=`expr "$APP_HOME" : '\(.*\)'` ||
APP_HOME="."

APP_PATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
CLASSPATH=$APP_PATH

exec java $JAVA_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
